import type { Metadata } from "next";
import Link from "next/link";
import { Accessibility, Car, ExternalLink, MapPin, Phone } from "lucide-react";
import { Container } from "@/components/layout/Container";
import { PageHero } from "@/components/ui/PageHero";
import { StoreHours } from "@/components/ui/StoreHours";
import { storeInfo } from "@/lib/storeInfo";

export const metadata: Metadata = { title: "Visit Us | Gamers N Geeks" };
const faqs = [["Do I need to register for events?","Many weekly events welcome walk-ins, while larger tournaments may require advance registration. Check the event listing or call the store."],["Can I bring my own games?","Absolutely. The play space is built for the community. Staff can help you find an open table and learn about scheduled events."],["Do you offer store pickup?","This demo shows how local pickup could be offered through Shopify, with live availability and pickup notifications."],["Is the store beginner-friendly?","Yes. New players are welcome, and the staff can help you choose a game, build a deck, or find an introductory event."]] as const;

export default function ContactPage(){return <main>
  <PageHero eyebrow="Contact & visit" title="Your next adventure is right down the road." description="Find the store, plan your visit, and step into Mobile's community hub for cards, miniatures, games, and organized play." imageSrc="/images/store/store-retail-floor.png" imageAlt="Inside the Gamers N Geeks store" />
  <section className="bg-background py-12 sm:py-16"><Container className="grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><div className="min-h-[28rem] overflow-hidden rounded-xl border border-border bg-surface"><iframe title="Map showing Gamers N Geeks in Mobile, Alabama" src={storeInfo.map.embedUrl} className="h-full min-h-[28rem] w-full border-0" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div><div className="rounded-xl border border-border bg-surface p-6 sm:p-8"><p className="text-sm font-bold uppercase tracking-[.16em] text-brand">Gamers N Geeks</p><address className="mt-4 not-italic leading-7 text-text-secondary"><p>{storeInfo.address.street}</p><p>{storeInfo.address.locality}</p></address><a href={storeInfo.phone.href} className="mt-5 inline-flex min-h-11 items-center gap-2 font-bold text-text-link"><Phone className="size-5" aria-hidden="true"/>{storeInfo.phone.display}</a><a href={storeInfo.map.directionsUrl} target="_blank" rel="noreferrer" className="mt-5 flex min-h-12 items-center justify-center gap-2 rounded-lg bg-brand px-5 font-bold text-on-brand">Get directions <ExternalLink className="size-4" aria-hidden="true"/></a><div className="mt-7 border-t border-border pt-6"><h2 className="text-xl font-bold">Store hours</h2><div className="mt-3"><StoreHours hours={storeInfo.hours}/></div></div></div></Container></section>
  <section className="bg-background-alt py-12 sm:py-16"><Container><div className="grid gap-4 md:grid-cols-3">{[[MapPin,"Easy to find","Located on Moffett Road in Mobile, with clear storefront access."],[Car,"Parking","Convenient lot parking is available directly outside the shopping center."],[Accessibility,"Accessibility","Ground-level entrance and spacious paths help make the store welcoming to everyone."]].map(([Icon,title,copy])=>{const ItemIcon=Icon as typeof MapPin; return <article key={String(title)} className="rounded-xl border border-border bg-surface p-6"><ItemIcon className="size-7 text-brand" aria-hidden="true"/><h2 className="mt-4 text-lg font-bold">{String(title)}</h2><p className="mt-2 text-sm leading-6 text-text-secondary">{String(copy)}</p></article>})}</div></Container></section>
  <section className="bg-background py-12 sm:py-16"><Container><p className="text-sm font-bold uppercase tracking-[.16em] text-brand">Good to know</p><h2 className="mt-2 text-3xl font-bold">Frequently asked questions</h2><div className="mt-7 grid gap-4 md:grid-cols-2">{faqs.map(([question,answer])=><article key={question} className="rounded-xl border border-border bg-surface p-6"><h3 className="text-lg font-bold">{question}</h3><p className="mt-3 text-sm leading-6 text-text-secondary">{answer}</p></article>)}</div></Container></section>
  <section className="bg-brand py-10 text-on-brand"><Container className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-2xl font-extrabold">Make a day of it.</h2><p className="mt-1">Browse the store, meet the staff, and stay for a game.</p></div><Link href="/events" className="inline-flex min-h-12 items-center justify-center rounded-lg bg-[#111] px-6 font-bold text-white">See upcoming events</Link></Container></section>
</main>}
