import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Brush, Dices, Heart, Swords, Trophy, Users } from "lucide-react";
import { Container } from "@/components/layout/Container";
import { DemoNote } from "@/components/ui/DemoNote";
import { PageHero } from "@/components/ui/PageHero";

export const metadata: Metadata = { title: "About | Gamers N Geeks" };
const pillars = [[Users,"Community first","A welcoming gathering place where new players and longtime regulars belong."],[Trophy,"Every way to play","Casual nights, competitive events, leagues, and special releases."],[Heart,"People who care","Friendly staff who know the games, remember the players, and love the hobby."]] as const;
const experiences = [[Swords,"Miniatures & competitive play"],[Brush,"Paint nights & hobby help"],[Dices,"Board games & role-playing"],[Users,"Trading cards & weekly leagues"]] as const;

export default function AboutPage(){return <main>
  <PageHero eyebrow="Our story" title="More than a store. It’s a community." description="Gamers N Geeks is where Mobile comes to discover a new hobby, sharpen a favorite strategy, and spend time with people who understand the joy of play." imageSrc="/images/store/store-retail-floor.png" imageAlt="The colorful retail floor inside Gamers N Geeks" />
  <section className="bg-background py-12 sm:py-16 lg:py-20"><Container className="grid gap-10 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-brand">Built around the table</p><h2 className="mt-2 text-3xl font-bold sm:text-4xl">A local game store should feel like your favorite campaign.</h2><p className="mt-5 leading-7 text-text-secondary">It starts with discovery, grows through shared experiences, and becomes a story people want to return to. Gamers N Geeks brings retail, organized play, and genuine hospitality together under one roof.</p><p className="mt-4 leading-7 text-text-secondary">Whether someone is opening their first booster, painting their hundredth miniature, or looking for a Friday night table, the store gives them a place to begin.</p></div><div className="relative aspect-[4/3] overflow-hidden rounded-xl border border-border"><Image src="/images/store/store-retail-floor.png" alt="Games, miniatures, and hobby supplies on the store floor" fill sizes="(max-width:1024px) 100vw,50vw" className="object-cover"/></div></Container></section>
  <section className="bg-background-alt py-12 sm:py-16"><Container><div className="grid gap-4 md:grid-cols-3">{pillars.map(([Icon,title,copy])=><article key={title} className="rounded-xl border border-border bg-surface p-6"><Icon className="size-8 text-brand" aria-hidden="true"/><h2 className="mt-5 text-xl font-bold">{title}</h2><p className="mt-3 text-sm leading-6 text-text-secondary">{copy}</p></article>)}</div><div className="mt-8"><DemoNote>Strong photography and an authentic story help a local business earn trust before a customer ever walks through the door. This page shows how the real store—not generic ecommerce—can lead the brand.</DemoNote></div></Container></section>
  <section className="bg-background py-12 sm:py-16 lg:py-20"><Container><div className="grid gap-10 lg:grid-cols-[1.1fr_1fr] lg:items-center"><div className="relative aspect-[16/10] overflow-hidden rounded-xl border border-border"><Image src="/images/store/store-event-hall.png" alt="Large gaming tables in the Gamers N Geeks event hall" fill sizes="(max-width:1024px) 100vw,55vw" className="object-cover"/></div><div><p className="text-sm font-bold uppercase tracking-[.16em] text-brand">Room to belong</p><h2 className="mt-2 text-3xl font-bold">The community is the main event.</h2><p className="mt-4 leading-7 text-text-secondary">A dedicated play space turns an inventory visit into a relationship. Events introduce players to products, staff expertise builds confidence, and shared nights create regular customers.</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{experiences.map(([Icon,title])=><div key={title} className="flex items-center gap-3 rounded-lg border border-border bg-surface p-4"><Icon className="size-6 shrink-0 text-brand" aria-hidden="true"/><span className="font-semibold">{title}</span></div>)}</div></div></div></Container></section>
  <section className="bg-brand py-10 text-on-brand"><Container className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-2xl font-extrabold">Come see what is happening.</h2><p className="mt-1">The best way to understand the store is to join the community for a night.</p></div><Link href="/events" className="inline-flex min-h-12 items-center justify-center rounded-lg bg-[#111] px-6 font-bold text-white">Explore events</Link></Container></section>
</main>}
